language: python
python:
  - "3.7"

cache:
  directories:
    - $HOME/.pip-cache/

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose coveralls responses coveralls
# command to run tests
script:
  - flake8 eero
  - py.test --cov=eero --cov-report=term

after_success:
  - coveralls

